# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GuessTheNumbers.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import random

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.min = 0
        self.max = 100
        self.guess = random.randint(self.min , self.max)
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(521, 452)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 501, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.computer_guesses_2 = QtWidgets.QTabWidget(self.centralwidget)
        self.computer_guesses_2.setGeometry(QtCore.QRect(10, 90, 501, 301))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.computer_guesses_2.sizePolicy().hasHeightForWidth())
        self.computer_guesses_2.setSizePolicy(sizePolicy)
        self.computer_guesses_2.setObjectName("computer_guesses_2")
        self.computer_guesses = QtWidgets.QWidget()
        self.computer_guesses.setObjectName("computer_guesses")
        self.result_board = QtWidgets.QLabel(self.computer_guesses)
        self.result_board.setGeometry(QtCore.QRect(20, 20, 451, 151))
        font = QtGui.QFont()
        font.setPointSize(80)
        self.result_board.setFont(font)
        self.result_board.setAlignment(QtCore.Qt.AlignCenter)
        self.result_board.setObjectName("result_board")
        self.correct_btn = QtWidgets.QPushButton(self.computer_guesses)
        self.correct_btn.setGeometry(QtCore.QRect(340, 180, 131, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.correct_btn.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.correct_btn.setFont(font)
        self.correct_btn.setAutoFillBackground(False)
        self.correct_btn.setObjectName("correct_btn")
        self.lower_btn = QtWidgets.QPushButton(self.computer_guesses)
        self.lower_btn.setGeometry(QtCore.QRect(180, 180, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lower_btn.setFont(font)
        self.lower_btn.setObjectName("lower_btn")
        self.higher_btn = QtWidgets.QPushButton(self.computer_guesses)
        self.higher_btn.setGeometry(QtCore.QRect(20, 180, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.higher_btn.setFont(font)
        self.higher_btn.setObjectName("higher_btn")
        self.computer_guesses_2.addTab(self.computer_guesses, "")
        self.human_guesses = QtWidgets.QWidget()
        self.human_guesses.setObjectName("human_guesses")
        self.label_2 = QtWidgets.QLabel(self.human_guesses)
        self.label_2.setGeometry(QtCore.QRect(24, 20, 451, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.result_guess = QtWidgets.QLabel(self.human_guesses)
        self.result_guess.setGeometry(QtCore.QRect(24, 199, 451, 61))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.result_guess.setFont(font)
        self.result_guess.setObjectName("result_guess")
        self.input = QtWidgets.QLineEdit(self.human_guesses)
        self.input.setGeometry(QtCore.QRect(22, 100, 441, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.input.setFont(font)
        self.input.setObjectName("input")
        self.computer_guesses_2.addTab(self.human_guesses, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 521, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.computer_guesses_2.setCurrentIndex(1)
        self.correct_btn.clicked.connect(self.correct)
        self.lower_btn.clicked.connect(self.go_lower)
        self.higher_btn.clicked.connect(self.go_higher)
        self.input.editingFinished.connect(self.check_correct)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def go_higher(self):
        self.min = int(self.result_board.text())
        self.result_board.setText(str(random.randint(self.min , self.max)))

    def go_lower(self):
        self.max = int(self.result_board.text())
        self.result_board.setText(str(random.randint(self.min , self.max)))
    
    def correct(self):
        self.result_board.setText("correct")

    def check_correct(self):
        self.answer = self.input.text()
        if self.answer != '':
            self.answer = int(self.answer)
            if self.answer > self.guess :
                self.result_guess.setText("go lower")
                self.input.clear()
            elif self.answer < self.guess :
                self.result_guess.setText("go higher")
                self.input.clear()
            else:
                self.result_guess.setText("correct")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Guess the Numbers"))
        self.label.setText(_translate("MainWindow", "lets play game"))
        self.result_board.setText(_translate("MainWindow", str(random.randint(self.min , self.max))))
        self.correct_btn.setText(_translate("MainWindow", "correct"))
        self.lower_btn.setText(_translate("MainWindow", "lower"))
        self.higher_btn.setText(_translate("MainWindow", "higher"))
        self.computer_guesses_2.setTabText(self.computer_guesses_2.indexOf(self.computer_guesses), _translate("MainWindow", "computer guesses"))
        self.label_2.setText(_translate("MainWindow", "enter your guess"))
        self.result_guess.setText(_translate("MainWindow", ""))
        self.computer_guesses_2.setTabText(self.computer_guesses_2.indexOf(self.human_guesses), _translate("MainWindow", "human guesses"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
